// Yee Tan , Yap Zi Ming
// C00278275,  C00425108
// CMPS 359 – Android Programming
// Final Programming Project
// Certificate of Authenticity:
//I certify that the code in this project are entirely my own work, the work of the members
//of my team or were caused to be generated by me or us.



package com.example.finalprojectsplit

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.example.finalprojectsplit.ui.main.MainFragment


var repository: BedrockURepository? = null
var adapter: FriendListingAdapter? = null
var adapter2: FriendExpenseListingAdapter? = null
var allFriends : LiveData<List<Friends>>? = null

lateinit var searchResults: MutableLiveData<List<Friends>>

class MainActivity : AppCompatActivity() {




    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)

        repository = BedrockURepository(application)
        allFriends = repository!!.allFriends
        searchResults = repository!!.friendsSearchResults
    }
}